// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-_DaahfBLeej5zmD7Xouz8If5zJBf2JI',
    appId: '1:959962535374:web:02875841ebda0a423e479f',
    messagingSenderId: '959962535374',
    projectId: 'autowala-6610e',
    authDomain: 'autowala-6610e.firebaseapp.com',
    databaseURL: 'https://autowala-6610e-default-rtdb.firebaseio.com',
    storageBucket: 'autowala-6610e.firebasestorage.app',
    measurementId: 'G-TW9BRQ27MF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-_DaahfBLeej5zmD7Xouz8If5zJBf2JI',
    appId: '1:959962535374:android:c58352db09fa08c13e479f',
    messagingSenderId: '959962535374',
    projectId: 'autowala-6610e',
    databaseURL: 'https://autowala-6610e-default-rtdb.firebaseio.com',
    storageBucket: 'autowala-6610e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1vhvtst3B6QxpAbKLzglgPUg2OdUI6YE',
    appId: '1:959962535374:ios:YOUR_IOS_APP_ID',
    messagingSenderId: '959962535374',
    projectId: 'autowala-6610e',
    databaseURL: 'https://autowala-6610e-default-rtdb.firebaseio.com',
    storageBucket: 'autowala-6610e.firebasestorage.app',
    iosBundleId: 'com.autowala.user',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1vhvtst3B6QxpAbKLzglgPUg2OdUI6YE',
    appId: '1:959962535374:ios:YOUR_IOS_APP_ID',
    messagingSenderId: '959962535374',
    projectId: 'autowala-6610e',
    databaseURL: 'https://autowala-6610e-default-rtdb.firebaseio.com',
    storageBucket: 'autowala-6610e.firebasestorage.app',
    iosBundleId: 'com.autowala.user',
  );
}